### ISSUE TITLE
Use asciinema.org for demo

### ISSUE THREAD

**Issue by Xuanwo** [tensorchord/envd-quick-start#5]
Please consider using https://asciinema.org/ for the shell operations demo.

**Comment by Xuanwo** [comment]
https://github.com/tensorchord/envd-quick-start/issues/4 contains a huge svg that could block entire page loading.

**Comment by gaocegege** [comment]
Actually we have the demo in asciinema.

https://asciinema.org/a/518270

But we also want a gif in README.

**Comment by gaocegege** [comment]
> #4 contains a huge svg that could block entire page loading.

The SVG is not huge. It is only <1MB. But it consumes 90% CPU in Chrome Linux, I am not sure why.

**Comment by Xuanwo** [comment]
> But we also want a gif in README.

We can embed asciinema in README

**Comment by gaocegege** [comment]
> > But we also want a gif in README.
> 
> We can embed asciinema in README

Yep we can. But it is not playable in Markdown.

**Comment by gaocegege** [comment]
https://github.com/jetpack-io/devbox 's demo is fancy.

**Comment by gaocegege** [comment]
Maybe we can use https://github.com/marionebl/svg-term-cli

**Comment by Xuanwo** [comment]
> https://github.com/jetpack-io/devbox 's demo is fancy.

It's 82K.

**Comment by Xuanwo** [comment]
> But it is not playable in Markdown.

I got it. Users need to jump to https://asciinema.org/a/518270 to watch.

[![asciicast](https://asciinema.org/a/518270.svg)](https://asciinema.org/a/518270)

**Comment by gaocegege** [comment]
Yep, it is one of the limitations of asciinema.

https://github.com/marionebl/svg-term-cli can help resolve this.

**Comment by Xuanwo** [comment]
![test](https://user-images.githubusercontent.com/5351546/187870975-2e511e28-f3d8-4195-bd24-7653f86dc061.svg)

**Comment by Xuanwo** [comment]
Works but still hurts the browser's performance. Maybe we should make the demo a bit simpler?

**Comment by gaocegege** [comment]
Yep. I am working on it.

**Comment by Xuanwo** [comment]
I'm trying https://github.com/asciinema/agg

**Comment by Xuanwo** [comment]
![demo](https://user-images.githubusercontent.com/5351546/187872338-9c114e7e-5e2e-4f32-a37d-eb1ee76d672c.gif)

**Comment by gaocegege** [comment]
> I'm trying https://github.com/asciinema/agg

I also tested this. The gif is not in high quality.

**Comment by VoVAllen** [comment]
If svg doesn't work, mp4 can also be a better choice than gif I think

**Comment by gaocegege** [comment]
![demo](https://user-images.githubusercontent.com/5100735/187891206-b32160f1-5f65-415e-869a-d314763d6f4b.svg)

**Comment by Xuanwo** [comment]
> ![demo](https://user-images.githubusercontent.com/5100735/187891206-b32160f1-5f65-415e-869a-d314763d6f4b.svg)

Smooth!
